# 04 Candidate Evaluation

Track C merges outputs from both experimental views. The goal is a clean, report-friendly comparison table with shared scoring, method notes, and a single ranking rule.

In [2]:
from pathlib import Path
import json
import sys

import numpy as np
import pandas as pd

SEARCH_ROOTS = [Path.cwd().resolve(), Path.cwd().resolve().parent]
PROJECT_ROOT = next(path for path in SEARCH_ROOTS if (path / "DAY2_data.txt").exists())
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from sparsetap_config import DEFAULT_CONFIG
from sparsetap_utils import (
    candidate_table,
    load_candidates,
    prepare_environment,
    rank_candidates,
    save_candidates,
    save_table,
)

config = DEFAULT_CONFIG
data, prefix = prepare_environment(config)

predictive_candidates = load_candidates(config.candidate_dir / "predictive_candidates.json")
rule_candidates = load_candidates(config.candidate_dir / "rule_recovery_candidates.json")
all_candidates = predictive_candidates + rule_candidates

ranked = rank_candidates(all_candidates, data=data, prefix=prefix, noise=config.noise_prob)
save_candidates(ranked, config.candidate_dir / "all_ranked_candidates.json")
ranking_table = candidate_table(ranked)
save_table(ranking_table, config.metrics_dir / "all_candidate_ranking.csv")

by_method = (
    ranking_table.sort_values(
        ["prefix consistent?", "log-likelihood", "accuracy", "number of taps"],
        ascending=[False, False, False, True],
    )
    .groupby(["track", "method"], as_index=False)
    .head(1)
)
display(by_method)
ranking_table.head(40)

,candidate_id,track,method,taps,W,prefix consistent?,log-likelihood,accuracy,number of taps,notes
0,predictive-single_lag_scan-e1e66a9f,predictive,single_lag_scan,[63],63,1,-353288.969727,0.500746,1,Simple one-lag agreement baseline.
1,predictive-xgboost-7951de25,predictive,xgboost,"[4, 6, 7, 8, 14, 16, 24, 30, 39, 42, 49, 51, 5...",63,1,-353535.730124,0.500285,14,Tree-based predictive baseline converted into ...
8,predictive-pair_scan-63433550,predictive,pair_scan,"[37, 62]",62,1,-354671.005524,0.501580,2,Pairwise XOR interaction screen.
18,predictive-logistic_l1-f57f338e,predictive,logistic_l1,"[2, 10, 18, 19, 23, 26, 27, 32, 37, 42, 44, 47...",62,0,-355588.732391,0.499874,16,Sparse linear next-bit baseline; useful for la...

,candidate_id,track,method,taps,W,prefix consistent?,log-likelihood,accuracy,number of taps,notes
0,predictive-single_lag_scan-e1e66a9f,predictive,single_lag_scan,[63],63,1,-353288.969727,0.500746,1,Simple one-lag agreement baseline.
1,predictive-xgboost-7951de25,predictive,xgboost,"[4, 6, 7, 8, 14, 16, 24, 30, 39, 42, 49, 51, 5...",63,1,-353535.730124,0.500285,14,Tree-based predictive baseline converted into ...
2,predictive-xgboost-7a9e8305,predictive,xgboost,"[6, 8, 14, 24, 30, 49, 54, 63]",63,1,-353663.269205,0.500047,8,Tree-based predictive baseline converted into ...
3,predictive-xgboost-35958e29,predictive,xgboost,"[4, 6, 8, 14, 16, 24, 30, 42, 49, 51, 54, 63]",63,1,-353747.833161,0.499889,12,Tree-based predictive baseline converted into ...
4,predictive-xgboost-89a212b5,predictive,xgboost,"[4, 6, 8, 14, 24, 30, 49, 51, 54, 63]",63,1,-353778.331637,0.499832,10,Tree-based predictive baseline converted into ...
5,predictive-xgboost-55abf4fa,predictive,xgboost,"[6, 8, 24, 30, 49, 54, 63]",63,1,-353781.104226,0.499826,7,Tree-based predictive baseline converted into ...
6,predictive-xgboost-0cadf70b,predictive,xgboost,"[4, 6, 8, 14, 16, 24, 30, 39, 42, 49, 51, 54, 63]",63,1,-353892.007775,0.499619,13,Tree-based predictive baseline converted into ...
7,predictive-xgboost-81f00df0,predictive,xgboost,"[6, 24, 30, 49, 54, 63]",63,1,-354154.017409,0.499130,6,Tree-based predictive baseline converted into ...
8,predictive-pair_scan-63433550,predictive,pair_scan,"[37, 62]",62,1,-354671.005524,0.501580,2,Pairwise XOR interaction screen.
9,predictive-pair_scan-aa100d2b,predictive,pair_scan,"[2, 62]",62,1,-355048.077590,0.500879,2,Pairwise XOR interaction screen.
10,predictive-xgboost-c7c9b008,predictive,xgboost,"[4, 6, 8, 14, 16, 24, 30, 49, 51, 54, 63]",63,0,-352971.508319,0.501339,11,Tree-based predictive baseline converted into ...
11,predictive-xgboost-bdfac00f,predictive,xgboost,"[6, 24, 30, 54, 63]",63,0,-353376.306272,0.500583,5,Tree-based predictive baseline converted into ...
12,predictive-xgboost-6307246a,predictive,xgboost,"[4, 6, 7, 8, 10, 14, 16, 24, 30, 39, 42, 49, 5...",63,0,-353431.758047,0.500479,15,Tree-based predictive baseline converted into ...
13,predictive-xgboost-6b680d81,predictive,xgboost,"[4, 6, 7, 8, 10, 14, 16, 24, 30, 39, 42, 49, 5...",63,0,-353690.995092,0.499995,16,Tree-based predictive baseline converted into ...
14,predictive-xgboost-e424b5c0,predictive,xgboost,"[6, 8, 14, 24, 30, 49, 51, 54, 63]",63,0,-354306.509788,0.498845,9,Tree-based predictive baseline converted into ...
15,predictive-pair_scan-1c6297da,predictive,pair_scan,"[42, 62]",62,0,-354901.130388,0.501152,2,Pairwise XOR interaction screen.
16,predictive-pair_scan-f7deabff,predictive,pair_scan,"[47, 62]",62,0,-354937.174041,0.501085,2,Pairwise XOR interaction screen.
17,predictive-pair_scan-4245ab2d,predictive,pair_scan,"[25, 62]",62,0,-355201.956264,0.500593,2,Pairwise XOR interaction screen.
18,predictive-logistic_l1-f57f338e,predictive,logistic_l1,"[2, 10, 18, 19, 23, 26, 27, 32, 37, 42, 44, 47...",62,0,-355588.732391,0.499874,16,Sparse linear next-bit baseline; useful for la...
19,predictive-logistic_l1-29976aa9,predictive,logistic_l1,"[2, 10, 18, 19, 23, 26, 27, 32, 37, 42, 44, 47...",62,0,-355588.732391,0.499874,16,Sparse linear next-bit baseline; useful for la...
20,predictive-logistic_l1-f5cac6e5,predictive,logistic_l1,"[2, 10, 18, 19, 23, 26, 27, 32, 37, 42, 44, 47...",62,0,-355588.732391,0.499874,16,Sparse linear next-bit baseline; useful for la...
21,predictive-logistic_l1-fe54edff,predictive,logistic_l1,"[2, 10, 18, 19, 23, 26, 27, 32, 37, 42, 44, 47...",62,0,-355588.732391,0.499874,16,Sparse linear next-bit baseline; useful for la...
22,predictive-logistic_l1-1db66f34,predictive,logistic_l1,"[2, 10, 18, 19, 23, 26, 27, 32, 37, 42, 44, 47...",62,0,-355588.732391,0.499874,16,Sparse linear next-bit baseline; useful for la...
23,predictive-logistic_l1-d388dbf7,predictive,logistic_l1,"[2, 10, 18, 19, 23, 26, 27, 32, 37, 42, 44, 47...",62,0,-355588.732391,0.499874,16,Sparse linear next-bit baseline; useful for la...
24,predictive-pair_scan-bdbeee3e,predictive,pair_scan,"[56, 62]",62,0,-355799.449134,0.499482,2,Pairwise XOR interaction screen.
25,predictive-pair_scan-1ad23726,predictive,pair_scan,"[34, 62]",62,0,-356262.471450,0.498621,2,Pairwise XOR interaction screen.
26,predictive-single_lag_scan-b611ba13,predictive,single_lag_scan,[62],62,0,-356324.854697,0.498505,1,Simple one-lag agreement baseline.
27,predictive-single_lag_scan-c1e6d745,predictive,single_lag_scan,[61],61,0,-356991.562603,0.500669,1,Simple one-lag agreement baseline.
28,predictive-single_lag_scan-a13b3ae8,predictive,single_lag_scan,[59],59,0,-361363.735654,0.499368,1,Simple one-lag agreement baseline.
29,predictive-single_lag_scan-0d704d2a,predictive,single_lag_scan,[58],58,0,-363210.180062,0.499346,1,Simple one-lag agreement baseline.
30,predictive-single_lag_scan-c30b698a,predictive,single_lag_scan,[57],57,0,-364948.493509,0.499520,1,Simple one-lag agreement baseline.
31,predictive-pair_scan-5093ea1f,predictive,pair_scan,"[50, 56]",56,0,-365763.534912,0.501358,2,Pairwise XOR interaction screen.
32,predictive-single_lag_scan-db228c1e,predictive,single_lag_scan,[56],56,0,-365800.964859,0.501290,1,Simple one-lag agreement baseline.
33,predictive-pair_scan-adf3ed54,predictive,pair_scan,"[2, 56]",56,0,-365986.728304,0.500955,2,Pairwise XOR interaction screen.
34,predictive-pair_scan-246be101,predictive,pair_scan,"[37, 56]",56,0,-366060.201905,0.500822,2,Pairwise XOR interaction screen.
35,predictive-pair_scan-280e899c,predictive,pair_scan,"[42, 56]",56,0,-366211.307990,0.500550,2,Pairwise XOR interaction screen.
36,predictive-pair_scan-bb8caf0e,predictive,pair_scan,"[32, 56]",56,0,-367130.421152,0.498893,2,Pairwise XOR interaction screen.
37,predictive-pair_scan-14ea9d8c,predictive,pair_scan,"[47, 56]",56,0,-367352.228249,0.498493,2,Pairwise XOR interaction screen.
38,predictive-single_lag_scan-360adb71,predictive,single_lag_scan,[55],55,0,-368624.746791,0.499505,1,Simple one-lag agreement baseline.
39,predictive-xgboost-35cf8973,predictive,xgboost,"[6, 24, 30, 54]",54,0,-369930.536398,0.500448,4,Tree-based predictive baseline converted into ...